name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Create ZIP package
        run: |
          cd wordpress-theme
          zip -r ../luxury-fashion-woocommerce.zip .
          mv luxury-fashion-woocommerce.zip ../../
          
      - name: Release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: ./luxury-fashion-woocommerce.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
